name: Merge check
on: [push, pull_request]
jobs:
  etcd-storage:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: UT for etcd
      run: |
        docker run -d -p 2379:2379 --name etcd quay.io/coreos/etcd etcd -name etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379
        while ! nc -z 127.0.0.1 2379; do
          sleep 1
        done
        export TEST_DB_KIND=etcd
        export TEST_DB_URI=127.0.0.1:2379
        go test $(go list ./... | grep -v mongo | grep -v third_party | grep -v examples) -cover -covermode atomic -coverprofile coverage.out
    - name: UT for embedded etcd
      run: |
        export TEST_DB_KIND=embedded_etcd
        export TEST_DB_URI=default=http://127.0.0.1:2380
        go test $(go list ./... | grep -v mongo | grep -v third_party | grep -v examples) -cover -covermode atomic -coverprofile coverage.out