name: Merge check
on: [push, pull_request]
jobs:
  mongo-storage:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: UT
      run: |
        sudo docker-compose -f ./examples/dev/docker-compose.yaml up -d
        sleep 20
        export TEST_DB_KIND=mongo
        export TEST_DB_URI=mongodb://kie:123@127.0.0.1:27017/servicecomb
        time go test -v $(go list ./... | grep -v etcd |  grep -v third_party | grep -v examples)
    - name: Build kie images
      run: |
        cd build
        time bash build_docker.sh